# Generated by Django 6.0.2 on 2026-02-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeeattendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField()),
                ('date', models.CharField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
